# Cloud Build configuration for Airtable Service (Node.js)
steps:
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/mobyapp-images/mobyapp-airtable:$BUILD_ID'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/mobyapp-images/mobyapp-airtable:latest'
      - '.'

  # Push image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/mobyapp-images/mobyapp-airtable'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'mobyapp-airtable'
      - '--image=us-central1-docker.pkg.dev/$PROJECT_ID/mobyapp-images/mobyapp-airtable:latest'
      - '--region=us-central1'
      - '--platform=managed'
      - '--port=3000'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--min-instances=0'
      - '--max-instances=10'
      - '--allow-unauthenticated'
      - '--set-env-vars=NODE_ENV=production,AIRTABLE_API_KEY=${_AIRTABLE_API_KEY},AIRTABLE_BASE_ID=${_AIRTABLE_BASE_ID},AIRTABLE_TABLE_NAME_PERSONALES=${_AIRTABLE_TABLE_NAME_PERSONALES},AIRTABLE_TABLE_NAME_PROYECTOS=${_AIRTABLE_TABLE_NAME_PROYECTOS},AIRTABLE_TABLE_NAME_USERS_APP=${_AIRTABLE_TABLE_NAME_USERS_APP},AIRTABLE_TABLE_NAME_PROYECTOS_APP=${_AIRTABLE_TABLE_NAME_PROYECTOS_APP}'

substitutions:
  _AIRTABLE_API_KEY: 'set-in-trigger'
  _AIRTABLE_BASE_ID: 'set-in-trigger'
  _AIRTABLE_TABLE_NAME_PERSONALES: 'set-in-trigger'
  _AIRTABLE_TABLE_NAME_PROYECTOS: 'set-in-trigger'
  _AIRTABLE_TABLE_NAME_USERS_APP: 'set-in-trigger'
  _AIRTABLE_TABLE_NAME_PROYECTOS_APP: 'set-in-trigger'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

timeout: '600s'

